/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Daryl Cui' at '3/11/17 4:06 PM' with Gradle 2.6
 *
 * @author Daryl Cui, @date 3/11/17 4:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
